[workspace]
members = [
  "attestor",
  "esplora-async-blockchain-provider",
  "js-interface-wallet",
  "dlc-memory-storage-provider",
  "dlc-link-manager",
  # "oracle-discovery",
  "wallet",
  "wasm-wallet",
  "clients",
  "storage/reader",
  "storage/writer",
  "storage/common",
  "storage/api",
  "it",
]
