[workspace]
members = [
    "oracle",
    "oracle-discovery",
    "wallet",
    "clients",
    "blockcypher-blockchain-provider",
    "storage/reader",
    "storage/writer",
    "storage/common",
    "storage/api",
    "it"
]
