[workspace]
members = [
    "esplora-async-blockchain-provider",
    "js-interface-wallet",
    "dlc-storage-provider",
    "oracle",
    "oracle-discovery",
    "wallet",
    "wasm-wallet",
    "clients",
    "storage/reader",
    "storage/writer",
    "storage/common",
    "storage/api",
    "it"
]
