version: "3.9"
services:
  wallet-backend:
    image: "${DOCKER_REGISTRY_PREFIX}prototype-wallet-backend:latest"
    env_file: .env
    ports:
      - "8085:8085"
    environment:
      - "RUST_BACKTRACE=full"
      - "RUST_LOG=debug"
      - "USE_SLED=$USE_SLED"
      - "STORAGE_API_ENABLED=$STORAGE_API_ENABLED"
      - "CONTRACT_CLEANUP_ENABLED=$CONTRACT_CLEANUP_ENABLED"
