version: "3.9"
services:
  dlc-router-wallet:
    image: "${DOCKER_PUBLIC_REGISTRY_PREFIX}dlc-router-wallet:latest"
    env_file: .env
    hostname: dlc-router-wallet
    container_name: dlc-router-wallet
    entrypoint: "/app/dlc-router-wallet"
    ports:
      - "8085:8085"
    environment:
      - "BITCOIN_NETWORK=$BITCOIN_NETWORK"
      - "BLOCKCHAIN_INTERFACE_URL=$BLOCKCHAIN_INTERFACE_URL"
      - "ELECTRUM_API_URL=$ELECTRUM_API_URL"
      - "FINGERPRINT=$FINGERPRINT"
      - "RUST_LOG=$RUST_LOG"
      - "RUST_BACKTRACE=$RUST_BACKTRACE"
      - "SLED_WALLET_PATH": "wallet_db"
      - "STORAGE_API_ENABLED=$STORAGE_API_ENABLED"
      - "STORAGE_API_ENDPOINT=$STORAGE_API_ENDPOINT"
      - "XPRIVATE_KEY=$XPRIVATE_KEY"
