[package]
name = "dlc-storage-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlc-storage-common = { path = "../common" }
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
