version: '3.9'
services:
  dlc-link-attestor:
    image: attestor
    ports:
      - 8801:8801
    environment:
      "STORAGE_API_ENABLED": "false"
      "STORAGE_API_ENDPOINT": "http://localhost:8100"
      # "SECRET_KEY_FILE": "secret1.key"
      "BRANCH": "attestor-manager"
      "PORT": "8801"
      "CHAIN_1": "ETH_GOERLI"
      "VERSION_1": "1"
      # Infura API key!
      # "API_KEY_1":
