set dotenv-load := true

default:
  just --list

test:
  cargo test
  AR=/opt/homebrew/opt/llvm/bin/llvm-ar CC=/opt/homebrew/opt/llvm/bin/clang wasm-pack test --node -- --features "console_error_panic_hook"

build:
  ./build_all.sh

run: build
  npm run run

run-multiple:
  just build && wait
  # ATTESTOR_XPRIV=$ATTESTOR_XPRIV_1 npm run run:1 &
  # ATTESTOR_XPRIV=$ATTESTOR_XPRIV_2 npm run run:2 &
  # ATTESTOR_XPRIV=$ATTESTOR_XPRIV_3 npm run run:3 && fg
  npm run run:1 &
  npm run run:2 &
  npm run run:3 && fg
