[package]
name = "dlc-clients"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "json"]}
serde = {version = "*", features = ["derive"]}
serde_json = "1.0.81"