[package]
name = "dlc-clients"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
dlc-link-manager = { path = "../dlc-link-manager" }
dlc-manager = { git = "https://github.com/dlc-link/rust-dlc", rev= "bd71461", features = ["use-serde"] }
log = "0.4.17"
reqwest = { version = "0.11.13", features = ["blocking", "json"]}
serde = {version = "*", features = ["derive"]}
serde_json = "1.0.81"
secp256k1-zkp = { version = "0.7.0", default-features = false}

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
