settings:
  solidity-branch: dev
  storage-api-endpoint: http://storageapi:8100
  dev-endpoints-enabled: true

evm-chains:

stx-chains:
  - network: mocknet
    version: 1
    endpoint: ws://stx-btc1.dlc.link:3999
