version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
