version: "3.9"
services:
  oracle:
    image: "${DOCKER_REGISTRY_PREFIX}dlc-link-stack:latest"
    env_file: .env
    profiles: ["oracle"]
    hostname: oracle
    ports:
      - "8080:8080"
    environment:
      - "RUST_BACKTRACE=1"
      - "RUST_LOG=debug"
      - "VAULT_SKIP_VERIFY=true"
      - "VAULT_ADDR=http://vault:8200"
      - "VAULT_TOKEN=myroot"
      - "VAULT_ENABLED=$VAULT_ENABLED"
    command:
      - "--asset-pair-config-file"
      - "/app/config/asset_pair.json"
      - "--oracle-config-file"
      - "/app/config/oracle.json"
      - "--secret-key-file"
      - "/app/config/secret.key"
    volumes:
      - "../config:/app/config"
    entrypoint: "/app/sibyls"
  wallet-backend:
    image: "${DOCKER_REGISTRY_PREFIX}dlc-link-stack:latest"
    env_file: .env
    hostname: wallet-backend
    profiles: ["wallet"]
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      - "RUST_BACKTRACE=1"
      - "RUST_LOG=debug"
      - "ORACLE_URL=http://oracle:8080"
    entrypoint: "/app/dlc-link-backend"
  vault:
    image: vault
    env_file: .env
    container_name: vault
    hostname: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_TOKEN: "my-root-token"
      VAULT_UNSEAL_KEY: "my-unseal-key"
    volumes:
      - ./data:/vault/data
