FROM public.ecr.aws/dlc-link/dlc-link-base:latest AS build

USER circleci
COPY ./storage /app/storage-api/

RUN sudo chown -R circleci:circleci /app

WORKDIR /app/storage-api/api/
RUN cargo build --release --bin storage-api

FROM debian:bullseye-slim AS dlc-link-stack
RUN apt-get update && apt-get install -y openssl libpq-dev ca-certificates && apt-get clean
COPY --from=build /app/storage-api/api/target/release/storage-api /app/storage-api
WORKDIR /app
ENTRYPOINT ["/app/storage-api"]
