[package]
authors = ["DLC.Link"]
edition = "2018"
name = "esplora-async-blockchain-provider"
version = "0.1.0"

[dependencies]
bdk = {version = "0.28.0", default-features = false, features = ["async-interface", "use-esplora-async"]}
bitcoin = {version = "0.29.2", features=["serde"]}
dlc-manager = { git = "https://github.com/dlc-link/rust-dlc", features = ["use-serde"] }
futures = {version = "0.3.28", default-features = false }
lightning = {version = "0.0.113" }
log = "0.4.14"
js-interface-wallet = { path = "../js-interface-wallet"}
reqwest = {git = "https://github.com/dlc-link/reqwest", branch = "add-wasm-timeout-to-request-builder",  features = ["json", "rustls-tls"]}
serde = {version = "*", features = ["derive"]}
wasm-bindgen-futures = { version = "0.4.34"}
