name: Build docker

on:
  push:
    branches: [ master, build-old-versions-to-docker ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: dlc-link-stack
        registry: 903295530547.dkr.ecr.us-east-1.amazonaws.com
        addLatest: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1
    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1
    # - name: Build, tag, and push full image to Amazon ECR
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: dlc-link-stack
    #     IMAGE_TAG: latest
    #   run: |
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    # - name: Login to Amazon ECR Public
    #   id: login-ecr-public
    #   uses: aws-actions/amazon-ecr-login@v1
    #   with:
    #     registry-type: public
    # - name: Build, tag, and push wallet docker image to Amazon ECR Public
    #   env:
      #   REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      #   REGISTRY_ALIAS: dlc-link
      #   REPOSITORY: dlc-protocol-wallet
      #   IMAGE_TAG: latest #${{ github.sha }}
      # run: |
      #   docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG -f wallet/Dockerfile .
      #   docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
