name: Build docker

on:
  push:
    branches: [ master, build-old-versions-to-docker ]

jobs:
  # build:
  #   name: Build Image
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out code
  #     uses: actions/checkout@v3
  #   - name: Build and push docker image
  #     uses: mr-smithers-excellent/docker-build-push@v6
  #     with:
  #       image: dlc-link-stack
  #       registry: 903295530547.dkr.ecr.us-east-1.amazonaws.com
  #       addLatest: true
  #       dockerfile: docker/Dockerfile
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
  build-wallet-public:
    name: Build wallet public
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    - name: Build and push docker image
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: dlc-link
        REPOSITORY: dlc-protocol-wallet
        IMAGE_TAG: ${{ github.ref }}
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest -f wallet/Dockerfile .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
